Learning.Admin.WebUI/Controllers/ManageTutorController.cs
using Learning.Admin.Abstract;
using Learning.Admin.WebUI.Models;
using Learning.Tutor.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Learning.Admin.WebUI.Controllers
{
    //[Authorize(ViewModel.Account.AuthorizationModel.Permissions.Administrator.Admin)]
    [Authorize(Roles = Entities.Config.RolesConstant.Admin)]
    public class ManageTutorController : Controller
    {
        private readonly ILogger<ManageTutorController> _logger;
        private readonly IManageTutorService _manageTutor;
        public ManageTutorController(ILogger<ManageTutorController> logger, IManageTutorService manageTutor)
        {
            _manageTutor = manageTutor;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _manageTutor.GetAllTutors());
        }
        public IActionResult RegisterTutor()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> RegisterTutor(TutorViewModel model)
        {

            var result = await _manageTutor.CreateTutor(model);
            if (result.Succeeded)
                return RedirectToAction("Tutors");
            else
            {
                foreach (var item in result.Errors)
                {

                    ModelState.AddModelError(item.Code, item.Description);
                }
                return View(model);
            }
        }
        public IActionResult Tutors()
        {
            return View();
        }
        public async Task<IActionResult> Partial_Tutor()
        {
            return PartialView(await _manageTutor.GetAllTutors());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Learning.Admin.WebUI/Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Learning Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Do mock exam Admin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ManageTutor" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ManageTutor" asp-action="RegisterTutor">Add Tutor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <style>
        input[type=text], input[type=password] {
            height: 27px;
            background: transparent;
            border: none;
            border-bottom:1px solid azure;
            display: block;
            width: 75%;
            color:azure;
        }

        body {
            background: repeating-linear-gradient( 91deg, #0582cbc2, black 1368px)
        }
        .btn-submit {
            border: 0px solid #e7c188;
            padding: 5px;
            display: block;
            border-radius: 5px;
            background: #062d4e;
            color: whitesmoke;
            width: 28%;
        }
        body form{
            font-size:small;
            color:azure;
        }
        label{
            color:cornsilk;
        }
        h1{
            color:azure;
        }
        input:focus{
            outline:none;
        }
        .pnl-login{
            background:#062d4e;
            padding:42px;
            border-radius:45px;
        }
    </style>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Learning.Admin.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/bootstrap-notify.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Learning.Admin.WebUI/Views/Shared/_Partial_Layout_Footer.cshtml
<footer class="footer-gap" id="footer">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="col-md-7"><p><img src="/images/footer.png" width="184" height="43" alt="" /></p></div><p class="footer-text">
                    Studious is the online education platform specialising in mock test preparation for Studious students.

                    We are passionate experts in online education. Our services include online exams, the Studious shop and Studious tuition.

                    Our products are designed to prepare students for a variety of Grammar School and Independent School examinations.
                </p>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <h5 class="news">Quick Links</h5>

                <ul class="list-unstyled quick-links">
                    <li><a href="/Home/Index"><i class="fa fa-angle-double-right"></i>Home</a></li>
                    <li><a href="https://www.fiverr.com/share/qb8D02"><i class="fa fa-angle-double-right"></i>About</a></li>
                    <li><a href="/Account/Login"><i class="fa fa-angle-double-right"></i>Parent Login</a></li>
                    <li><a href="/Tutor/Dashboard"><i class="fa fa-angle-double-right"></i>Tutor Login</a></li>
                    <li><a href="/admin"><i class="fa fa-angle-double-right"></i>Admin</a></li>
                </ul>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <h5 class="news">Newsletter</h5><p class="footer-text">
                    Get all the latest information on events, sales and offers.
                    Sign up for newsletter today.
                </p><p><input type="button" value="Subscribe" class="subscribe"></p>
            </div>

            <!-- <div class="col-md-12 col-sm-12 col-xs-12"><h5 class="news">Payment Partners</h5><p><img src="images/payment.png" width="295" height="108" alt="" class="img-fluid"/>
             </p></div> -->


        </div>

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <h5 class="news">Payment Partners</h5>
                <img src="/images/payment.png" width="295" height="108" alt="" class="img-fluid2" />
            </div>
            <hr>
        </div>

    </div>

</footer>